easy_admin:
    site_name: 'ADACVG'
    list:
        actions:
            - {name: 'edit', icon: 'pencil', label: 'Edit'}
            - {name: 'delete', icon: 'trash', label: 'Delete'}
            - {name: 'search', icon: 'search', label: 'Search'}
            - {name: 'new', icon: 'plus', label: 'New'}
            - {name: 'show', icon: 'eye', label: 'Show'}

    entities:
        Article:
            class: App\Entity\Article
            label: 'Articles'
            list:
                title: 'Articles'
                fields:
                    - id
                    - date
                    - { property: 'title', label: 'Titre' }
                    #- { property: 'firstImage', type: 'image', label: 'Image', base_path: '%app.path.article_images%' }
                    - { property: 'images', template: 'vich_uploader_image_list.html.twig' }

            show:
                title: 'Article #%%entity_id%%'
                fields:
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', label: 'Texte' }
                    - { property: 'images', template: 'vich_uploader_image.html.twig' }



            new:
                title: 'Ajouter un article'
                fields:
                    - date
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', label: 'Texte'}
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType', by_reference: false}}

            edit:
                title: 'Article #%%entity_id%%'
                fields:
                    - date
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', type: 'Hillrange\CKEditor\Form\CKEditorType', label: 'Texte' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType', by_reference: false}}


        Event:
            class: App\Entity\Event
            label: 'Calendrier'
            list:
                title: 'Calendrier'
                fields:
                    - id
                    - { property: 'name', label: 'Evènement' }
                    - date
                    - { property: 'time', label: 'Heure' }
                    - { property: 'place', label: 'Lieu' }
            show:
                title: 'Evenement #%%entity_id%%'
                fields:
                    - { property: 'name', label: 'Evènement' }
                    - date
                    - { property: 'time', label: 'Heure' }
                    - { property: 'place', label: 'Lieu' }


            new:
                title: 'Ajouter un évènement'
                fields:
                    - { property: 'name', label: 'Evènement' }
                    - date
                    - { property: 'time', label: 'Heure' }
                    - { property: 'place', label: 'Lieu' }
            edit:
                title: 'Evènement #%%entity_id%%'
                fields:
                    - { property: 'name', label: 'Evènement' }
                    - date
                    - { property: 'time', label: 'Heure' }
                    - { property: 'place', label: 'Lieu' }



        User:
            class: App\Entity\User
            label: 'Abonnés'
            list:
                title: 'Abonnés'
                fields:
                    - id
                    - { property: 'username', label: 'Nom' }
                    - { property: 'email', type: 'email' }

            show:
                title: 'Abonné #%%entity_id%%'
                fields:
                    - { property: 'username', label: 'Nom' }
                    - email

            new:
                title: 'Ajouter un abonné'
                fields:
                    - { property: 'username', label: 'Nom' }
                    - email

            edit:
                title: 'Abonné #%%entity_id%%'
                fields:
                    - { property: 'username', label: 'Nom' }
                    - email



